name: Test self-hosted runner in org
on: [ push, workflow_dispatch ]

jobs:
  test-action-job:
    runs-on: ubuntu-20.04
    name: Check for org runner
    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Check self hosted runner
        id: check_runner
        uses: ./
        with:
          runner_location: redhat-actions
          github_pat: ${{ secrets.ORG_TOKEN }}

      - run: |
          echo "Runner exists: ${{ steps.check_runner.outputs.runner_present }}"
