name: Test self-hosted runner in repo
on: [ push, workflow_dispatch, pull_request_target ]

jobs:
  install-runner:
    runs-on: ubuntu-20.04
    name: Install repo runner
    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - uses: redhat-actions/oc-login@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: diagrawa-code
          insecure_skip_tls_verify: true

      - name: Install self hosted runner into repository
        uses: ./
        with:
          github_pat: ${{ secrets.REPO_TOKEN }}
          runner_labels: repo-label, repo-label-2

  test-selfhosted:
    runs-on: [ self-hosted, repo-label, repo-label-2 ]
    needs: install-runner

    steps:
      - run: "hostname"
